services:
  - type: web
    name: django-api
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      cd web
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: cd web && gunicorn web.wsgi
    healthCheckPath: /admin/login/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: web.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "django-api-05y3.onrender.com"
      - key: FRONTEND_ORIGINS
        value: "https://tu-front.pages.dev"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-clean-2025-10-27   # <-- NUEVO nombre
          property: connectionString

databases:
  - name: postgres-clean-2025-10-27        # <-- Igual al de arriba
    plan: free
